types = [
	'Grass', 'Poison', 'Flying', 'Fire', 'Bug', 'Water',
	'Normal', 'Ground', 'Fighting', 'Psychic', 'Rock', 'Dragon',
	'Ice', 'Ghost', 'Electric', 'Steel'
	]

types.each { |type| Type.create(name: type) }


abilities = [
	'Adaptability', 'Aerilate', 'Aftermath', 'Air Lock', 'Analytic',
	'Anger Point', 'Anticipation', 'Arena Trap', 'Aroma Veil', 'Aura Break',
	'Bad Dreams', 'Battle Armor', 'Big Pecks', 'Blaze', 'Bulletproof', 'Cheek Pouch',
	'Chlorophyll', 'Clear Body', 'Cloud Nine', 'Color Change', 'Competitive',
	'Compound Eyes', 'Contrary', 'Cursed Body', 'Cute Charm', 'Damp', 'Dark Aura',
	'Defeatist', 'Defiant', 'Download', 'Drizzle', 'Drought', 'Dry Skin', 'Early Bird',
	'Effect Spore', 'Fairy Aura', 'Filter', 'Flame Body', 'Flare Boost', 'Flash Fire',
	'Flower Gift', 'Flower Veil', 'Forecast', 'Forewarn', 'Friend Guard', 'Frisk',
	'Fur Coat', 'Gale Wings', 'Gluttony', 'Gooey', 'Grass Pelt', 'Guts', 'Harvest',
	'Healer', 'Heatproof', 'Heavy Metal', 'Honey Gather', 'Huge Power', 'Hustle',
	'Hydration', 'Hyper Cutter', 'Ice Body', 'Illuminate', 'Illusion', 'Immunity',
	'Imposter', 'Infiltrator', 'Inner Focus', 'Insomnia', 'Intimidate', 'Iron Barbs',
	'Iron Fist', 'Justified', 'Keen Eye', 'Klutz', 'Leaf Guard', 'Levitate',
	'Light Metal', 'Lightning Rod', 'Limber', 'Liquid Ooze', 'Magic Bounce', 'Magic Guard',
	'Magician', 'Magma Armor', 'Magnet Pull', 'Marvel Scale', 'Mega Launcher', 'Minus',
	'Mold Breaker', 'Moody', 'Motor Drive', 'Moxie', 'Multiscale', 'Multitype', 'Mummy',
	'Natural Cure', 'No Guard', 'Normalize', 'Oblivious', 'Overcoat', 'Overgrow', 'Own Tempo',
	'Parental Bond', 'Pickpocket', 'Pickup', 'Pixilate', 'Plus', 'Poison Heal', 'Poison Point',
	'Poison Touch', 'Prankster', 'Pressure', 'Protean', 'Pure Power', 'Quick Feet', 'Rain Dish',
	'Rattled', 'Reckless', 'Refrigerate', 'Regenerator', 'Rivalry', 'Rock Head', 'Rough Skin',
	'Run Away', 'Sand Force', 'Sand Rush', 'Sand Stream', 'Sand Veil', 'Sap Sipper', 'Scrappy',
	'Serene Grace', 'Shadow Tag', 'Shed Skin', 'Sheer Force', 'Shell Armor', 'Shield Dust',
	'Simple', 'Skill Link', 'Slow Start', 'Sniper', 'Snow Cloak', 'Snow Warning', 'Solar Power',
	'Solid Rock', 'Soundproof', 'Speed Boost', 'Stall', 'Stance Change', 'Static', 'Steadfast',
	'Stench', 'Sticky Hold', 'Storm Drain', 'Strong Jaw', 'Sturdy', 'Suction Cups', 'Super Luck',
	'Swarm', 'Sweet Veil', 'Swift Swim', 'Symbiosis', 'Synchronize', 'Tangled Feet', 'Technician',
	'Telepathy', 'Teravolt', 'Thick Fat', 'Tinted Lens', 'Torrent', 'Tough Claws', 'Toxic Boost',
	'Trace', 'Truant', 'Turboblaze', 'Unaware', 'Unburden', 'Unnerve', 'Victory Star',
	'Vital Spirit', 'Volt Absorb', 'Water Absorb', 'Water Veil', 'Weak Armor', 'White Smoke',
	'Wonder Guard', 'Wonder Skin', 'Zen Mode'
]

abilities.each {|ability| Ability.create(name: ability)}

Pokemon.create(name: 'Bulbasaur', evolves_at: 16, ability_id: 102)
Pokemon.create(name: 'Ivysaur', evolves_at: 32, ability_id: 102)
Pokemon.create(name: 'Venasaur', evolves_at: 'N/A', ability_id: 102)
Pokemon.create(name: 'Charmander', evolves_at: 16, ability_id: 14)
Pokemon.create(name: 'Charmeleon', evolves_at: 36, ability_id: 14)
Pokemon.create(name: 'Charizard', evolves_at: 'N/A', ability_id: 102)
Pokemon.create(name: 'Squirtle', evolves_at: 16, ability_id: 170)
Pokemon.create(name: 'Wartortle', evolves_at: 36, ability_id: 170)
Pokemon.create(name: 'Blastoise', evolves_at: 'N/A', ability_id: 170)
Pokemon.create(name: 'Caterpie', evolves_at: 7, ability_id: 137)
Pokemon.create(name: 'Metapod', evolves_at: 10, ability_id: 134)
Pokemon.create(name: 'Butterfree', evolves_at: 'N/A', ability_id: 22)
Pokemon.create(name: 'Weedle', evolves_at: 7, ability_id: 137)
Pokemon.create(name: 'Kakuna', evolves_at: 10, ability_id: 134)
Pokemon.create(name: 'Beedrill', evolves_at: 'N/A', ability_id: 159)
Pokemon.create(name: 'Pidgey', evolves_at: 18, ability_id: 74)
Pokemon.create(name: 'Pidgeotto', evolves_at: 36, ability_id: 74)
Pokemon.create(name: 'Pidgeot', evolves_at: 'N/A', ability_id: 22)
Pokemon.create(name: 'Rattata', evolves_at: 20, ability_id: 125)
Pokemon.create(name: 'Raticate', evolves_at: 'N/A', ability_id: 125)
Pokemon.create(name: 'Spearow', evolves_at: 20, ability_id: 74)
Pokemon.create(name: 'Fearow', evolves_at: 'N/A', ability_id: 74)
Pokemon.create(name: 'Ekans', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Arbok', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Pikachu', evolves_at: 'Thunderstone', ability_id: 150)
Pokemon.create(name: 'Raichu', evolves_at: 'N/A', ability_id: 150)
Pokemon.create(name: 'Sandshrew', evolves_at: 22, ability_id: 129)
Pokemon.create(name: 'Sandslash', evolves_at: 'N/A', ability_id: 129)
Pokemon.create(name: 'Nidoran (female)', evolves_at: 16, ability_id: 74)
Pokemon.create(name: 'Nidorina', evolves_at: 'Moonstone', ability_id: 22)
Pokemon.create(name: 'Nidoqueen', evolves_at: 'N/A', ability_id: 125)
Pokemon.create(name: 'Nidoran (male)', evolves_at: 16, ability_id: 74)
Pokemon.create(name: 'Nidorino', evolves_at: 'Moonstone', ability_id: 22)
Pokemon.create(name: 'Nidoking', evolves_at: 'N/A', ability_id: 125)
Pokemon.create(name: 'Clefairy', evolves_at: 'Moonstone', ability_id: 25)
Pokemon.create(name: 'Clefable', evolves_at: 'N/A', ability_id: 25)
Pokemon.create(name: 'Vulpix', evolves_at: 'Firestone', ability_id: 40)
Pokemon.create(name: 'Ninetales', evolves_at: 'N/A', ability_id: 40)
Pokemon.create(name: 'Jigglypuff', evolves_at: 'Moonstone', ability_id: 25)
Pokemon.create(name: 'Wigglytuff', evolves_at: 'N/A', ability_id: 25)
Pokemon.create(name: 'Zubat', evolves_at: 22, ability_id: 67)
Pokemon.create(name: 'Golbat', evolves_at: 'N/A', ability_id: 67)
Pokemon.create(name: 'Oddish', evolves_at: 17, ability_id: 17)
Pokemon.create(name: 'Gloom', evolves_at: 21, ability_id: 17)
Pokemon.create(name: 'Vileplume', evolves_at: 'N/A', ability_id: 17)
Pokemon.create(name: 'Paras', evolves_at: 24, ability_id: 35)
Pokemon.create(name: 'Parasect', evolves_at: 'N/A', ability_id: 35)
Pokemon.create(name: 'Venonat', evolves_at: 31, ability_id: 22)
Pokemon.create(name: 'Venomoth', evolves_at: 31, ability_id: 137)
Pokemon.create(name: 'Diglett', evolves_at: 26, ability_id: 129)
Pokemon.create(name: 'Dugtrio', evolves_at: 'N/A', ability_id: 129)
Pokemon.create(name: 'Meowth', evolves_at: 28, ability_id: 106)
Pokemon.create(name: 'Persian', evolves_at: 'N/A', ability_id: 80)
Pokemon.create(name: 'Psyduck', evolves_at: 33, ability_id: 26)
Pokemon.create(name: 'Golduck', evolves_at: 'N/A', ability_id: 26)
Pokemon.create(name: 'Mankey', evolves_at: 28, ability_id: 180)
Pokemon.create(name: 'Primeape', evolves_at: 'N/A', ability_id: 180)
Pokemon.create(name: 'Growlithe', evolves_at: 'Firestone', ability_id: 70)
Pokemon.create(name: 'Arcanine', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Poliwag', evolves_at: 25, ability_id: 182)
Pokemon.create(name: 'Poliwhirl', evolves_at: 'Water Stone', ability_id: 182)
Pokemon.create(name: 'Poliwrath', evolves_at: 'N/A', ability_id: 182)
Pokemon.create(name: 'Abra', evolves_at: 16, ability_id: 163)
Pokemon.create(name: 'Kadabra', evolves_at: 'By Trade', ability_id: 163)
Pokemon.create(name: 'Alakazam', evolves_at: 'N/A', ability_id: 163)
Pokemon.create(name: 'Machop', evolves_at: 28, ability_id: 52)
Pokemon.create(name: 'Machoke', evolves_at: 'By Trade', ability_id: 52)
Pokemon.create(name: 'Machamp', evolves_at: 'N/A', ability_id: 52)
Pokemon.create(name: 'Bellsprout', evolves_at: 21, ability_id: 17)
Pokemon.create(name: 'Weepinbell', evolves_at: 'Leafstone', ability_id: 17)
Pokemon.create(name: 'Victreebel', evolves_at: 'N/A', ability_id: 17)
Pokemon.create(name: 'Tentacool', evolves_at: 30, ability_id: 18)
Pokemon.create(name: 'Tentacruel', evolves_at: 'N/A', ability_id: 18)
Pokemon.create(name: 'Geodude', evolves_at: 25, ability_id: 123)
Pokemon.create(name: 'Graveler', evolves_at: 'By Trade', ability_id: 123)
Pokemon.create(name: 'Golem', evolves_at: 'N/A', ability_id: 123)
Pokemon.create(name: 'Ponyta', evolves_at: 40, ability_id: 124)
Pokemon.create(name: 'Rapidash', evolves_at: 'N/A', ability_id: 124)
Pokemon.create(name: 'Slowpoke', evolves_at: 37, ability_id: 100)
Pokemon.create(name: 'Slowking', evolves_at: 'King\'s Rock', ability_id: 100)
Pokemon.create(name: 'Slowbro', evolves_at: 'N/A', ability_id: 100)
Pokemon.create(name: 'Magnemite', evolves_at: 30, ability_id: 86)
Pokemon.create(name: 'Magneton', evolves_at: 'N/A', ability_id: 86)
Pokemon.create(name: 'Doduo', evolves_at: 31, ability_id: 124)
Pokemon.create(name: 'Dodrio', evolves_at: 'N/A', ability_id: 124)
Pokemon.create(name: 'Seel', evolves_at: 34, ability_id: 167)
Pokemon.create(name: 'Dewgong', evolves_at: 'N/A', ability_id: 124)
Pokemon.create(name: 'Grimer', evolves_at: 38, ability_id: 152)
Pokemon.create(name: 'Muk', evolves_at: 'N/A', ability_id: 152)
Pokemon.create(name: 'Shelder', evolves_at: 'Waterstone', ability_id: 136)
Pokemon.create(name: 'Cloyster', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Gastly', evolves_at: 25, ability_id: 77)
Pokemon.create(name: 'Haunter', evolves_at: 'By Trade', ability_id: 136)
Pokemon.create(name: 'Gengar', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Onix', evolves_at: 'N/A', ability_id: 123)
Pokemon.create(name: 'Drowzee', evolves_at: 26, ability_id: 123)
Pokemon.create(name: 'Hypno', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Krabby', evolves_at: 28, ability_id: 60)
Pokemon.create(name: 'Kingler', evolves_at: 'N/A', ability_id: 60)
Pokemon.create(name: 'Voltorb', evolves_at: 30, ability_id: 136)
Pokemon.create(name: 'Electrode', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Exeggcute', evolves_at: 'Leafstone', ability_id: 17)
Pokemon.create(name: 'Exeggutor', evolves_at: 'N/A', ability_id: 17)
Pokemon.create(name: 'Cubone', evolves_at: 28, ability_id: 136)
Pokemon.create(name: 'Marowak', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Hitmonlee', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Hitmonchan', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Lickitung', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Koffing', evolves_at: 35, ability_id: 136)
Pokemon.create(name: 'Weezing', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Rhyhorn', evolves_at: 42, ability_id: 136)
Pokemon.create(name: 'Rhyperior', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Chansey', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Tangela', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Horsea', evolves_at: 32, ability_id: 136)
Pokemon.create(name: 'Seadra', evolves_at: 'Dragon Scale', ability_id: 136)
Pokemon.create(name: 'Kingdra', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Goldeen', evolves_at: 33, ability_id: 136)
Pokemon.create(name: 'Seaking', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Staryu', evolves_at: 'Waterstone', ability_id: 136)
Pokemon.create(name: 'Starmie', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Mr. Mime', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Scyther', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Jynx', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Magmar', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Electabuzz', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Pinsir', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Tauros', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Magikarp', evolves_at: 20, ability_id: 136)
Pokemon.create(name: 'Gyrados', evolves_at: 'N/A', ability_id: 136)
Pokemon.create(name: 'Lapras', evolves_at: 'N/A', ability_id: 182)
Pokemon.create(name: 'Ditto', evolves_at: 'N/A', ability_id: 80)
Pokemon.create(name: 'Eevee', evolves_at: 'Firestone, Waterstone, or Thunderstone', ability_id: 70)
Pokemon.create(name: 'Vaporeon', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Jolteon', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Flareon', evolves_at: 'N/A', ability_id: 150)
Pokemon.create(name: 'Porygon', evolves_at: 'N/A', ability_id: 150)
Pokemon.create(name: 'Omanyte', evolves_at: 40, ability_id: 129)
Pokemon.create(name: 'Omastar', evolves_at: 'N/A', ability_id: 129)
Pokemon.create(name: 'Kabuto', evolves_at: 40, ability_id: 74)
Pokemon.create(name: 'Kabutops', evolves_at: 'N/A', ability_id: 22)
Pokemon.create(name: 'Aerodactyl', evolves_at: 'N/A', ability_id: 125)
Pokemon.create(name: 'Snorlax', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Articuno', evolves_at: 'N/A', ability_id: 70)
Pokemon.create(name: 'Zapdos', evolves_at: 'N/A', ability_id: 150)
Pokemon.create(name: 'Moltres', evolves_at: 'N/A', ability_id: 150)
Pokemon.create(name: 'Dratini', evolves_at: 30, ability_id: 129)
Pokemon.create(name: 'Dragonair', evolves_at: 55, ability_id: 129)
Pokemon.create(name: 'Dragonite', evolves_at: 'N/A', ability_id: 74)
Pokemon.create(name: 'Mewtwo', evolves_at: 'N/A', ability_id: 22)
Pokemon.create(name: 'Mew', evolves_at: 'N/A', ability_id: 125)

PokemonType.create(pokemon_id: 1, type_id: 1)
PokemonType.create(pokemon_id: 1, type_id: 2)
PokemonType.create(pokemon_id: 2, type_id: 1)
PokemonType.create(pokemon_id: 2, type_id: 2)
PokemonType.create(pokemon_id: 3, type_id: 1)
PokemonType.create(pokemon_id: 3, type_id: 2)
PokemonType.create(pokemon_id: 4, type_id: 4)
PokemonType.create(pokemon_id: 5, type_id: 4)
PokemonType.create(pokemon_id: 6, type_id: 4)
PokemonType.create(pokemon_id: 6, type_id: 3)
PokemonType.create(pokemon_id: 7, type_id: 6)
PokemonType.create(pokemon_id: 8, type_id: 6)
PokemonType.create(pokemon_id: 9, type_id: 6)
PokemonType.create(pokemon_id: 10, type_id: 5)
PokemonType.create(pokemon_id: 11, type_id: 5)
PokemonType.create(pokemon_id: 12, type_id: 5)
PokemonType.create(pokemon_id: 12, type_id: 3)
PokemonType.create(pokemon_id: 13, type_id: 2)
PokemonType.create(pokemon_id: 13, type_id: 5)
PokemonType.create(pokemon_id: 14, type_id: 2)
PokemonType.create(pokemon_id: 14, type_id: 5)
PokemonType.create(pokemon_id: 15, type_id: 2)
PokemonType.create(pokemon_id: 15, type_id: 5)
PokemonType.create(pokemon_id: 16, type_id: 3)
PokemonType.create(pokemon_id: 16, type_id: 7)
PokemonType.create(pokemon_id: 17, type_id: 3)
PokemonType.create(pokemon_id: 17, type_id: 7)
PokemonType.create(pokemon_id: 18, type_id: 3)
PokemonType.create(pokemon_id: 18, type_id: 7)
PokemonType.create(pokemon_id: 19, type_id: 7)
PokemonType.create(pokemon_id: 20, type_id: 7)
PokemonType.create(pokemon_id: 21, type_id: 3)
PokemonType.create(pokemon_id: 21, type_id: 7)
PokemonType.create(pokemon_id: 22, type_id: 3)
PokemonType.create(pokemon_id: 22, type_id: 7)
PokemonType.create(pokemon_id: 23, type_id: 2)
PokemonType.create(pokemon_id: 24, type_id: 2)
PokemonType.create(pokemon_id: 25, type_id: 15)
PokemonType.create(pokemon_id: 26, type_id: 15)
PokemonType.create(pokemon_id: 27, type_id: 8)
PokemonType.create(pokemon_id: 28, type_id: 8)
PokemonType.create(pokemon_id: 29, type_id: 2)
PokemonType.create(pokemon_id: 30, type_id: 2)
PokemonType.create(pokemon_id: 31, type_id: 2)
PokemonType.create(pokemon_id: 31, type_id: 8)
PokemonType.create(pokemon_id: 32, type_id: 2)
PokemonType.create(pokemon_id: 33, type_id: 2)
PokemonType.create(pokemon_id: 34, type_id: 2)
PokemonType.create(pokemon_id: 34, type_id: 8)
PokemonType.create(pokemon_id: 35, type_id: 7)
PokemonType.create(pokemon_id: 36, type_id: 7)
PokemonType.create(pokemon_id: 37, type_id: 4)
PokemonType.create(pokemon_id: 38, type_id: 4)
PokemonType.create(pokemon_id: 39, type_id: 7)
PokemonType.create(pokemon_id: 40, type_id: 7)
PokemonType.create(pokemon_id: 41, type_id: 2)
PokemonType.create(pokemon_id: 41, type_id: 3)
PokemonType.create(pokemon_id: 42, type_id: 2)
PokemonType.create(pokemon_id: 42, type_id: 3)
PokemonType.create(pokemon_id: 43, type_id: 1)
PokemonType.create(pokemon_id: 43, type_id: 2)
PokemonType.create(pokemon_id: 44, type_id: 1)
PokemonType.create(pokemon_id: 44, type_id: 2)
PokemonType.create(pokemon_id: 45, type_id: 1)
PokemonType.create(pokemon_id: 45, type_id: 2)
PokemonType.create(pokemon_id: 46, type_id: 1)
PokemonType.create(pokemon_id: 46, type_id: 5)
PokemonType.create(pokemon_id: 47, type_id: 1)
PokemonType.create(pokemon_id: 47, type_id: 5)
PokemonType.create(pokemon_id: 48, type_id: 2)
PokemonType.create(pokemon_id: 48, type_id: 5)
PokemonType.create(pokemon_id: 49, type_id: 2)
PokemonType.create(pokemon_id: 49, type_id: 5)
PokemonType.create(pokemon_id: 50, type_id: 8)
PokemonType.create(pokemon_id: 51, type_id: 8)
PokemonType.create(pokemon_id: 52, type_id: 7)
PokemonType.create(pokemon_id: 53, type_id: 7)
PokemonType.create(pokemon_id: 54, type_id: 6)
PokemonType.create(pokemon_id: 55, type_id: 6)
PokemonType.create(pokemon_id: 56, type_id: 9)
PokemonType.create(pokemon_id: 57, type_id: 9)
PokemonType.create(pokemon_id: 58, type_id: 4)
PokemonType.create(pokemon_id: 59, type_id: 4)
PokemonType.create(pokemon_id: 60, type_id: 6)
PokemonType.create(pokemon_id: 61, type_id: 6)
PokemonType.create(pokemon_id: 62, type_id: 6)
PokemonType.create(pokemon_id: 62, type_id: 9)
PokemonType.create(pokemon_id: 63, type_id: 10)
PokemonType.create(pokemon_id: 64, type_id: 10)
PokemonType.create(pokemon_id: 65, type_id: 10)
PokemonType.create(pokemon_id: 66, type_id: 9)
PokemonType.create(pokemon_id: 67, type_id: 9)
PokemonType.create(pokemon_id: 68, type_id: 9)
PokemonType.create(pokemon_id: 69, type_id: 1)
PokemonType.create(pokemon_id: 69, type_id: 2)
PokemonType.create(pokemon_id: 70, type_id: 1)
PokemonType.create(pokemon_id: 70, type_id: 2)
PokemonType.create(pokemon_id: 71, type_id: 1)
PokemonType.create(pokemon_id: 71, type_id: 2)
PokemonType.create(pokemon_id: 72, type_id: 6)
PokemonType.create(pokemon_id: 72, type_id: 2)
PokemonType.create(pokemon_id: 73, type_id: 6)
PokemonType.create(pokemon_id: 73, type_id: 2)
PokemonType.create(pokemon_id: 74, type_id: 11)
PokemonType.create(pokemon_id: 74, type_id: 8)
PokemonType.create(pokemon_id: 75, type_id: 11)
PokemonType.create(pokemon_id: 75, type_id: 8)
PokemonType.create(pokemon_id: 76, type_id: 11)
PokemonType.create(pokemon_id: 76, type_id: 8)
PokemonType.create(pokemon_id: 77, type_id: 4)
PokemonType.create(pokemon_id: 78, type_id: 4)
PokemonType.create(pokemon_id: 79, type_id: 6)
PokemonType.create(pokemon_id: 79, type_id: 10)
PokemonType.create(pokemon_id: 80, type_id: 6)
PokemonType.create(pokemon_id: 80, type_id: 10)
PokemonType.create(pokemon_id: 81, type_id: 15)
PokemonType.create(pokemon_id: 81, type_id: 16)
PokemonType.create(pokemon_id: 82, type_id: 15)
PokemonType.create(pokemon_id: 82, type_id: 16)
PokemonType.create(pokemon_id: 83, type_id: 7)
PokemonType.create(pokemon_id: 83, type_id: 3)
PokemonType.create(pokemon_id: 84, type_id: 7)
PokemonType.create(pokemon_id: 84, type_id: 3)
PokemonType.create(pokemon_id: 85, type_id: 7)
PokemonType.create(pokemon_id: 85, type_id: 3)
PokemonType.create(pokemon_id: 86, type_id: 6)
PokemonType.create(pokemon_id: 87, type_id: 6)
PokemonType.create(pokemon_id: 87, type_id: 13)
PokemonType.create(pokemon_id: 88, type_id: 2)
PokemonType.create(pokemon_id: 89, type_id: 2)
PokemonType.create(pokemon_id: 90, type_id: 6)
PokemonType.create(pokemon_id: 91, type_id: 6)
PokemonType.create(pokemon_id: 91, type_id: 13)
PokemonType.create(pokemon_id: 92, type_id: 14)
PokemonType.create(pokemon_id: 92, type_id: 2)
PokemonType.create(pokemon_id: 93, type_id: 14)
PokemonType.create(pokemon_id: 93, type_id: 2)
PokemonType.create(pokemon_id: 94, type_id: 14)
PokemonType.create(pokemon_id: 94, type_id: 2)
PokemonType.create(pokemon_id: 95, type_id: 11)
PokemonType.create(pokemon_id: 95, type_id: 8)
PokemonType.create(pokemon_id: 96, type_id: 10)
PokemonType.create(pokemon_id: 97, type_id: 10)
PokemonType.create(pokemon_id: 98, type_id: 6)
PokemonType.create(pokemon_id: 99, type_id: 6)
PokemonType.create(pokemon_id: 100, type_id: 15)
PokemonType.create(pokemon_id: 101, type_id: 15)
PokemonType.create(pokemon_id: 102, type_id: 1)
PokemonType.create(pokemon_id: 102, type_id: 10)
PokemonType.create(pokemon_id: 103, type_id: 1)
PokemonType.create(pokemon_id: 103, type_id: 10)
PokemonType.create(pokemon_id: 104, type_id: 8)
PokemonType.create(pokemon_id: 105, type_id: 8)
PokemonType.create(pokemon_id: 106, type_id: 9)
PokemonType.create(pokemon_id: 107, type_id: 9)
PokemonType.create(pokemon_id: 108, type_id: 7)
PokemonType.create(pokemon_id: 109, type_id: 2)
PokemonType.create(pokemon_id: 110, type_id: 2)
PokemonType.create(pokemon_id: 111, type_id: 11)
PokemonType.create(pokemon_id: 111, type_id: 8)
PokemonType.create(pokemon_id: 112, type_id: 11)
PokemonType.create(pokemon_id: 112, type_id: 8)
PokemonType.create(pokemon_id: 113, type_id: 7)
PokemonType.create(pokemon_id: 114, type_id: 1)
PokemonType.create(pokemon_id: 115, type_id: 7)
PokemonType.create(pokemon_id: 116, type_id: 6)
PokemonType.create(pokemon_id: 117, type_id: 6)
PokemonType.create(pokemon_id: 118, type_id: 6)
PokemonType.create(pokemon_id: 119, type_id: 6)
PokemonType.create(pokemon_id: 120, type_id: 6)
PokemonType.create(pokemon_id: 121, type_id: 6)
PokemonType.create(pokemon_id: 121, type_id: 10)
PokemonType.create(pokemon_id: 122, type_id: 10)
PokemonType.create(pokemon_id: 123, type_id: 5)
PokemonType.create(pokemon_id: 123, type_id: 3)
PokemonType.create(pokemon_id: 124, type_id: 13)
PokemonType.create(pokemon_id: 124, type_id: 10)
PokemonType.create(pokemon_id: 125, type_id: 15)
PokemonType.create(pokemon_id: 126, type_id: 4)
PokemonType.create(pokemon_id: 127, type_id: 5)
PokemonType.create(pokemon_id: 128, type_id: 7)
PokemonType.create(pokemon_id: 129, type_id: 6)
PokemonType.create(pokemon_id: 130, type_id: 6)
PokemonType.create(pokemon_id: 130, type_id: 3)
PokemonType.create(pokemon_id: 131, type_id: 6)
PokemonType.create(pokemon_id: 131, type_id: 13)
PokemonType.create(pokemon_id: 132, type_id: 7)
PokemonType.create(pokemon_id: 133, type_id: 7)
PokemonType.create(pokemon_id: 134, type_id: 6)
PokemonType.create(pokemon_id: 135, type_id: 15)
PokemonType.create(pokemon_id: 136, type_id: 4)
PokemonType.create(pokemon_id: 137, type_id: 7)
PokemonType.create(pokemon_id: 138, type_id: 11)
PokemonType.create(pokemon_id: 138, type_id: 6)
PokemonType.create(pokemon_id: 139, type_id: 11)
PokemonType.create(pokemon_id: 139, type_id: 6)
PokemonType.create(pokemon_id: 140, type_id: 11)
PokemonType.create(pokemon_id: 140, type_id: 6)
PokemonType.create(pokemon_id: 141, type_id: 11)
PokemonType.create(pokemon_id: 141, type_id: 6)
PokemonType.create(pokemon_id: 142, type_id: 11)
PokemonType.create(pokemon_id: 142, type_id: 3)
PokemonType.create(pokemon_id: 143, type_id: 7)
PokemonType.create(pokemon_id: 144, type_id: 13)
PokemonType.create(pokemon_id: 144, type_id: 3)
PokemonType.create(pokemon_id: 145, type_id: 15)
PokemonType.create(pokemon_id: 145, type_id: 3)
PokemonType.create(pokemon_id: 146, type_id: 4)
PokemonType.create(pokemon_id: 146, type_id: 3)
PokemonType.create(pokemon_id: 147, type_id: 12)
PokemonType.create(pokemon_id: 148, type_id: 12)
PokemonType.create(pokemon_id: 149, type_id: 12)
PokemonType.create(pokemon_id: 149, type_id: 3)
PokemonType.create(pokemon_id: 150, type_id: 10)
PokemonType.create(pokemon_id: 151, type_id: 10)







